[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 999999
via_ir = true
solc = "0.8.19"
verbosity = 2
ffi = true

remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  'forge-std/=lib/forge-std/src/'
]

[profile.intense.fuzz]
runs = 10000
max_test_rejects = 999999

[fmt]
line_length = 160
number_underscore = "thousands"



[etherscan]
bnb = { key = "${SCAN_API_KEY}",chain = 97,url="https://testnet.bscscan.com" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
